#ifndef COLORGORICAL_COLOR_NAMES_H
#define COLORGORICAL_COLOR_NAMES_H

extern int COLORGORICAL_NAMES_CCOUNT[8325];
extern int COLORGORICAL_NAMES_TCOUNT[153];
extern int COLORGORICAL_NAMES_T[1273725];

#endif
